### PR TITLE
8.0.0

### PR DESCRIPTION
**Pull request by marcus-j-davies**
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/240
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/232
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/231
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/226
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/241
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/247
Fixes https://github.com/zwave-js/node-red-contrib-zwave-js/issues/242

### CODE REVIEW

**Comment by velocityzen** [comment]
Hello

When are you going to merge this?

**Comment by crxporter** [comment]
Release is planned shortly after `node-zwave-js` moves version 10.0 from beta to release. Could be any day now.

If you want to start using version 8 beta, here's how:
1- navigate to the folder where you've installed nodered (usually on a pi this is `~/.node-red/` )
2- run the following install command:
```
npm i node-red-contrib-zwave-js@beta
```
3- restart nodered

As always, please come back here and report any issues! Thanks!

**Comment by marcus-j-davies** [comment]
I have 1 thing to work on (Small UI Updates with the FW wizard)
But I agree, shortly after the v10 release of the driver.

**Comment by marcus-j-davies** [comment]
Just a courtesy message for those monitoring this PR.

v8 is 1 task away from being released (slight update to the UI for FW updates).
The last change is being worked on with @crxporter, so it's very much on my mind.

But, I am now on vacation for a week.
Once I'm back, I'll get this done and dusted.

For those who ant access now, see [here](https://github.com/zwave-js/node-red-contrib-zwave-js/pull/243#issuecomment-1225595562)

**Comment by crxporter** [comment]
Are you done yet?

😬

**Comment by marcus-j-davies** [comment]
> Are you done with this yet?
> 
> 😬

BETA 5 will be up in a few minutes (I'm hoping this is it before going for a public release)

I'll notify about BETA 5 on discord and here -> https://github.com/zwave-js/node-red-contrib-zwave-js/discussions/248

**Comment by marcus-j-davies** [comment]
Final BETA is up

**Comment by crxporter** [comment]
> Final BETA is up

Careful with that word "final"

**Pull request merged**
