### PR TITLE
7.0.0

### PR DESCRIPTION
**Pull request by marcus-j-davies**
# node-red-contrib-zwave-js V7

**Breaking Changes**
   - The **GET_VALUE_RESPONSE** object is no longer partitioned with **response** and **valueId** properties.
       Instead, the returned object now represents a shape simular to **VALUE_UPDATED** events.
       The value will now be attached to the **currentValue** property, along with the Value ID on the same level.
   - The **VALUE_DB** objects are no longer partitioned with **currentValue** and **valueId** properties.
       Instead, the returned objects now include the Value ID on the same level as **currentValue**
   - Much like above, **GET_VALUE_METADATA_RESPONSE** has also been simplified, where the result is attached to **metadata**, with the Value ID on the same level.

**New Features**
   - **VALUE_UPDATED**, **VALUE_NOTIFICATION**, **GET_VALUE_RESPONSE** and **VALUE_DB** now contain a **normalizedObject** property.
       This property aims to make it easy to utilise the value change, in that it summarises the event with easy to understand property names.
   - New UI Layout - We have overhauled the UI, and focused on making it fit more into the node red style guide.
   - An entierly new User Interface to render a Network Mesh Map.
   - Network statistics now include route information that is obtained during communication, and is used
       as the basis of the new map.
   - Multiple ZWave sticks/Networks are now supported (finally)
        - all message will contain a property of **networkId** to indentify the source network.
   - Improved Recovery when the USB/ZWave transceiver has been removed/re-introduced.
        - This is possible with a custom Watchdog implmentation, this introduces a new event type of **WATCHDOG**
         Which will describe what is happening. 

**Fixes**
   - Nodes that are not marked as ready can now be removed correctly.
   - Fix potential issue when httpAdminRoot has a custom value.
   - various performance, stability and optimisations to the UI.
   - UI Interaction is no longer picked up by Device Nodes.

**Changes**
   - Bump serialport to V10
   - Bump ZWJS to V9
   - New mapping algorithm - The new algorithm results in a much needed accuracy improvement, and is far superior to previous methods.
   - Nodes have now been named more clearly
   - Live Camera QR Code Scanning has been removed

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
**Feedback**
 - [ ] Put Notice about the map being built up overtime (especially for Battery operated Device

**Comment by fabnavigator** [comment]
For the Binary Switch configurtion, I don't see the point of displaying "FALSE" after "Target value". Just "Target Value" seems sufficient. Also, I don't want to have to click on the pencil, I would like to click anywhere on the highlighted Target value row to get the set TRUE/FALSE options.

**Comment by fabnavigator** [comment]
When I click on a node in the network map it display information about that node. When I click on the controller node, if ignores my click and till shows information for the last node I had selected.

**Comment by fabnavigator** [comment]
From Z-Wave configuration I'm clicking to see my nodes. As I click through my nodes (and I wait for the properties to be fetched before I click on another), I'm gettiing a "Cound not fetch value." dialog box after a bit. Blank inside. Then everything goes away. I have to refresh the page to get back to my flow. I also see a "Could not fetch value Metadata" grayed out dialog with no OK button. Last thing before I have to refresh the page.

**Comment by fabnavigator** [comment]
I'm sorry to say, it's not intuitive to me that I need to click two times on a node in the node list to set the node options. Double clicking isn't normally required on web pages. Once I click on a node, it brings up the information for that node. There should be something there that I can click on to see the node options. Like in 6.5.5. I get a hand cursor when I hover over the node number, but it doesn't do anything when I click on it.

**Comment by marcus-j-davies** [comment]
> I'm sorry to say, it's not intuitive to me that I need to click two times on a node in the node list to set the node options. Double clicking isn't normally required on web pages. Once I click on a node, it brings up the information for that node. There should be something there that I can click on to see the node options. Like in 6.5.5. I get a hand cursor when I hover over the node number, but it doesn't do anything when I click on it.

Hi @fabnavigator, we currently can't commit to a change here. 

This was brought in to address a problem that prevented dead nodes being able to get removed. I also have to be careful with the real estate that's available (or not i should say)

Previously a node needed to be selected to access other options.
This is now via a double click - to prevent it needing to be selected.

A double click reveals options - but does not select the target node.

**Comment by marcus-j-davies** [comment]
**node-red-contrib-zwave-js V7 BETA 2** is up.

 - Put Notice about the map being built up overtime (especially for Battery operated Devices)
 - Improvements to sluggish Node options mech
   - Single click : Node Select
   - A 2nd Click : Show Options
   - Shift+Click  : Show Options (Without Select)
 - Fix Controller in the Map UI 
 - Adjustment to timeout mechanics to allow slower systems to respond.
 - Add waiting feedback for Association MGMT and Remove Failed Node
 
 To install:
 

```
 cd ./.node-red
 npm install node-red-contrib-zwave-js@beta --force
```
 
  Note to Docker Users - the .node-red directly maybe different , i.e `/data`

**Pull request merged**
